name: speech_recognition
description: A flutter plugin to use the speech recognition on iOS and Android
version: 0.3.0+1
author: Erick Ghaumez <erick@rxla.bz>
homepage: https://github.com/rxlabz/speech_recognition
environment:
  sdk: '>=2.0.0 <3.0.0'
flutter:
  plugin:
    androidPackage: bz.rxla.flutter.speechrecognition
    pluginClass: SpeechRecognitionPlugin

dependencies:
  flutter:
    sdk: flutter
